--------------------------------------------------------------------------------
-- CLYVO VET - ChallengeAPI
-- script_bd.sql
--
-- DDL + carga inicial de dados do banco de dados Oracle utilizado pela solucao.
-- Reflete exatamente o schema gerado pelas EF Core Migrations do projeto
-- (Migrations/20260512192211_InitialCreate.cs), com comentarios adicionados
-- para documentacao (requisito da Entrega - 3o Sprint / DevOps Tools & Cloud
-- Computing, item 3.3).
--
-- Tabelas representam o CORE do negocio da CLYVO VET (jornada de saude do pet):
--   TUTORES   -> donos dos pets
--   PETS      -> animais cadastrados, vinculados a um tutor
--   VACINAS   -> vacinas aplicadas em cada pet
--   CONSULTAS -> consultas veterinarias realizadas em cada pet
--
-- Ordem de execucao: TUTORES -> PETS -> VACINAS / CONSULTAS (respeita as FKs)
--
-- Este script roda tanto manualmente via sqlplus quanto automaticamente na
-- primeira inicializacao do container Oracle (ver docker/Dockerfile.oracle,
-- que o copia para /container-entrypoint-initdb.d/). Nesse caso a imagem
-- gvenzl/oracle-xe executa o arquivo como usuario SYS - por isso o primeiro
-- comando troca o schema atual para SYSTEM, que e o usuario usado pela API
-- na connection string (User Id=system).
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

--------------------------------------------------------------------------------
-- 1. LIMPEZA (permite reexecutar o script em um banco ja provisionado)
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Consultas" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Vacinas" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pets" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Tutores" CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------------------------------------
-- 2. TABELA: TUTORES
--------------------------------------------------------------------------------
CREATE TABLE "Tutores" (
    "Id"       NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "Nome"     NVARCHAR2(2000) NOT NULL,
    "Telefone" NVARCHAR2(2000) NOT NULL,
    "Email"    NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_Tutores" PRIMARY KEY ("Id")
);

COMMENT ON TABLE "Tutores" IS 'Donos/responsaveis pelos pets cadastrados na CLYVO VET';
COMMENT ON COLUMN "Tutores"."Id" IS 'Identificador unico do tutor (PK)';
COMMENT ON COLUMN "Tutores"."Nome" IS 'Nome completo do tutor';
COMMENT ON COLUMN "Tutores"."Telefone" IS 'Telefone de contato do tutor';
COMMENT ON COLUMN "Tutores"."Email" IS 'E-mail de contato do tutor';

--------------------------------------------------------------------------------
-- 3. TABELA: PETS
--------------------------------------------------------------------------------
CREATE TABLE "Pets" (
    "Id"        NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "Nome"      NVARCHAR2(2000) NOT NULL,
    "Especie"   NVARCHAR2(2000) NOT NULL,
    "Raca"      NVARCHAR2(2000) NOT NULL,
    "Idade"     NUMBER(10)      NOT NULL,
    "TutorId"   NUMBER(10)      NOT NULL,
    "ClinicaId" NUMBER(10)      NOT NULL,
    CONSTRAINT "PK_Pets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pets_Tutores_TutorId" FOREIGN KEY ("TutorId")
        REFERENCES "Tutores" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Pets_TutorId" ON "Pets" ("TutorId");

COMMENT ON TABLE "Pets" IS 'Pets cadastrados, cada um vinculado a um tutor';
COMMENT ON COLUMN "Pets"."Id" IS 'Identificador unico do pet (PK)';
COMMENT ON COLUMN "Pets"."Nome" IS 'Nome do pet';
COMMENT ON COLUMN "Pets"."Especie" IS 'Especie do pet (ex: Cao, Gato)';
COMMENT ON COLUMN "Pets"."Raca" IS 'Raca do pet';
COMMENT ON COLUMN "Pets"."Idade" IS 'Idade do pet, em anos';
COMMENT ON COLUMN "Pets"."TutorId" IS 'FK para Tutores.Id - tutor responsavel pelo pet';
COMMENT ON COLUMN "Pets"."ClinicaId" IS 'Identificador da clinica CLYVO VET responsavel pelo atendimento do pet';

--------------------------------------------------------------------------------
-- 4. TABELA: VACINAS
--------------------------------------------------------------------------------
CREATE TABLE "Vacinas" (
    "Id"             NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "NomeVacina"     NVARCHAR2(2000) NOT NULL,
    "DataAplicacao"  NVARCHAR2(2000) NOT NULL,
    "ProximaDose"    NVARCHAR2(2000) NOT NULL,
    "PetId"          NUMBER(10)      NOT NULL,
    CONSTRAINT "PK_Vacinas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vacinas_Pets_PetId" FOREIGN KEY ("PetId")
        REFERENCES "Pets" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Vacinas_PetId" ON "Vacinas" ("PetId");

COMMENT ON TABLE "Vacinas" IS 'Vacinas aplicadas em cada pet, com previsao da proxima dose';
COMMENT ON COLUMN "Vacinas"."Id" IS 'Identificador unico da vacina aplicada (PK)';
COMMENT ON COLUMN "Vacinas"."NomeVacina" IS 'Nome/tipo da vacina aplicada';
COMMENT ON COLUMN "Vacinas"."DataAplicacao" IS 'Data em que a vacina foi aplicada';
COMMENT ON COLUMN "Vacinas"."ProximaDose" IS 'Data prevista para a proxima dose/reforco';
COMMENT ON COLUMN "Vacinas"."PetId" IS 'FK para Pets.Id - pet que recebeu a vacina';

--------------------------------------------------------------------------------
-- 5. TABELA: CONSULTAS
--------------------------------------------------------------------------------
CREATE TABLE "Consultas" (
    "Id"            NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "DataConsulta"  NVARCHAR2(2000) NOT NULL,
    "Descricao"     NVARCHAR2(2000) NOT NULL,
    "Veterinario"   NVARCHAR2(2000) NOT NULL,
    "PetId"         NUMBER(10)      NOT NULL,
    CONSTRAINT "PK_Consultas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Consultas_Pets_PetId" FOREIGN KEY ("PetId")
        REFERENCES "Pets" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Consultas_PetId" ON "Consultas" ("PetId");

COMMENT ON TABLE "Consultas" IS 'Consultas veterinarias realizadas para cada pet';
COMMENT ON COLUMN "Consultas"."Id" IS 'Identificador unico da consulta (PK)';
COMMENT ON COLUMN "Consultas"."DataConsulta" IS 'Data em que a consulta foi realizada';
COMMENT ON COLUMN "Consultas"."Descricao" IS 'Descricao/motivo da consulta';
COMMENT ON COLUMN "Consultas"."Veterinario" IS 'Nome do veterinario responsavel pelo atendimento';
COMMENT ON COLUMN "Consultas"."PetId" IS 'FK para Pets.Id - pet atendido na consulta';

--------------------------------------------------------------------------------
-- 6. CARGA DE DADOS (dados significativos, minimo exigido: 2 linhas/tabela
--    usadas no CRUD; aqui entregamos 5 por tabela para dar margem confortavel
--    e permitir uma demonstracao mais rica no video)
--------------------------------------------------------------------------------
INSERT INTO "Tutores" ("Nome", "Telefone", "Email") VALUES ('Gustavo Vieira', '11988887777', 'gustavo@clyvovet.com.br');
INSERT INTO "Tutores" ("Nome", "Telefone", "Email") VALUES ('Rafael Souza', '11977776666', 'rafael@clyvovet.com.br');
INSERT INTO "Tutores" ("Nome", "Telefone", "Email") VALUES ('Marina Alves', '11966665555', 'marina@clyvovet.com.br');
INSERT INTO "Tutores" ("Nome", "Telefone", "Email") VALUES ('Bruno Lima', '11955554444', 'bruno@clyvovet.com.br');
INSERT INTO "Tutores" ("Nome", "Telefone", "Email") VALUES ('Carla Nogueira', '11944443333', 'carla@clyvovet.com.br');

INSERT INTO "Pets" ("Nome", "Especie", "Raca", "Idade", "TutorId", "ClinicaId") VALUES ('Thor', 'Cao', 'Labrador', 3, 1, 1);
INSERT INTO "Pets" ("Nome", "Especie", "Raca", "Idade", "TutorId", "ClinicaId") VALUES ('Mimi', 'Gato', 'SRD', 2, 2, 1);
INSERT INTO "Pets" ("Nome", "Especie", "Raca", "Idade", "TutorId", "ClinicaId") VALUES ('Bidu', 'Cao', 'Poodle', 5, 3, 1);
INSERT INTO "Pets" ("Nome", "Especie", "Raca", "Idade", "TutorId", "ClinicaId") VALUES ('Luna', 'Gato', 'Siames', 1, 4, 1);
INSERT INTO "Pets" ("Nome", "Especie", "Raca", "Idade", "TutorId", "ClinicaId") VALUES ('Rex', 'Cao', 'Bulldog', 4, 5, 1);

INSERT INTO "Vacinas" ("NomeVacina", "DataAplicacao", "ProximaDose", "PetId") VALUES ('V10', '2026-01-10', '2027-01-10', 1);
INSERT INTO "Vacinas" ("NomeVacina", "DataAplicacao", "ProximaDose", "PetId") VALUES ('Antirrabica', '2026-02-15', '2027-02-15', 2);
INSERT INTO "Vacinas" ("NomeVacina", "DataAplicacao", "ProximaDose", "PetId") VALUES ('Giardia', '2026-03-05', '2026-09-05', 3);
INSERT INTO "Vacinas" ("NomeVacina", "DataAplicacao", "ProximaDose", "PetId") VALUES ('V4', '2026-04-20', '2027-04-20', 4);
INSERT INTO "Vacinas" ("NomeVacina", "DataAplicacao", "ProximaDose", "PetId") VALUES ('Antirrabica', '2026-05-01', '2027-05-01', 5);

INSERT INTO "Consultas" ("DataConsulta", "Descricao", "Veterinario", "PetId") VALUES ('2026-06-01', 'Checkup de rotina', 'Dra. Ana Paula', 1);
INSERT INTO "Consultas" ("DataConsulta", "Descricao", "Veterinario", "PetId") VALUES ('2026-06-10', 'Vomito e falta de apetite', 'Dr. Marcos Vinicius', 2);
INSERT INTO "Consultas" ("DataConsulta", "Descricao", "Veterinario", "PetId") VALUES ('2026-07-02', 'Avaliacao dermatologica', 'Dra. Ana Paula', 3);
INSERT INTO "Consultas" ("DataConsulta", "Descricao", "Veterinario", "PetId") VALUES ('2026-07-18', 'Consulta pos-vacina', 'Dr. Marcos Vinicius', 4);
INSERT INTO "Consultas" ("DataConsulta", "Descricao", "Veterinario", "PetId") VALUES ('2026-08-22', 'Avaliacao cardiologica', 'Dra. Ana Paula', 5);

COMMIT;

--------------------------------------------------------------------------------
-- 7. CONSULTAS DE VERIFICACAO (uteis para o video de demonstracao - rodar
--    dentro do container Oracle via sqlplus, conforme README.md)
--------------------------------------------------------------------------------
-- SELECT * FROM "Tutores" ORDER BY "Id";
-- SELECT * FROM "Pets" ORDER BY "Id";
-- SELECT * FROM "Vacinas" ORDER BY "Id";
-- SELECT * FROM "Consultas" ORDER BY "Id";
